GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpdGFsaW5oaGFAZ21haWwuY29tIiwiaWF0IjoxNzE3MzQxOTEzLCJleHAiOjE3MTk5MzM5MTN9.uUY5fBgjo5d9652j08HE-w4zeIv0X6hz0HV6VBBB4X0

